language: node_js
node_js: node
before_deploy: npm run lint
deploy:
  provider: npm
  email: j.m.clerck@icloud.com
  api_key:
    secure: P+wJ7UFmZ82iMG+hmdXVDwUpCWFPDAcibTTWUQ3L20GwE+JMEL3QQGFpIznbHhFHPOEgOotqahDWOURaPaR4wDRWbasMjpjYettAK2eLZqAxdHDJbLKu4vjk8ybmxxGtTfb4trzAvJ4IsvU1nDs+gbpQZVTdqolI8fyNeWlkdVL0jinYJ4mAJ0thq1sZTN7ezm+8Hrgzx8J93ruLXTHMx+Xdx5SJ+Wh8GFs0tTc5cNT/IVPHk7nvz/AtLgVYUcDE+QqE6teGpFiojfqHZue7Is4H/4hK/RargfWEntQb0f6sn7PlsFJA1X1viWaJPWRxi4lwu+Udiv1Rj1KvgCP271UgvKDltHgv9u72/OMA8EJ7LQyb3BRD2MRoFOKJm3nzk9II8FgkdzSH4whko0vVmbJIwTaSf5TCNxngAQAcypgx25d3j1qBiRxm7jtu2e5tmjVEwbHgbfvCGF2ZC9+uHHpXFsIRlGIjv0wE0YT/DuK0AcaIlb2LU+ulZv8DLYRr7lCYOEjk4pIzWYWDBKrY3tWEiqI4I2RtBjNfWFo6ty5ICYW6kceyT8XKAXDGxSoI223pxpGk6RR/rnWye7ELH3NE1MsFUjCT4GAWsdaOf+1VFQW3HHMTFq5yv99oIq+k+acqXuPDqJubV7hQZT4vYeOpjVVacWMnAnA0q9OKYwc=
  on:
    tags: true
    repo: Jmclerck/hyper-touchbar-switcher
